### ISSUE TITLE
Step 1.3 - Add platform cannot find module 'dezalgo'

### ISSUE THREAD

**Issue by GTTeric** [DAB0mB/angular-meteor-whatsapp#54]
![image](https://user-images.githubusercontent.com/31456851/36070247-e8a6e884-0eab-11e8-8ad6-717f34d6a584.png)

Step 3 of the Whatsapp tutorial doesn't work regardless of whether I try to install the iOS simulator or the Android emulator. Keep getting the above error. I even 'meteor npm install'ed that module and it still doesn't work. Google was also no help.

Anyone know what's going on?

EDIT: [This](https://guide.meteor.com/mobile.html#installing-prerequisites) link would be helpful to have in the tutorial... Especially since meteor is only compatible with certain versions. I already have Android Studio installed so I will try to replace the tools folder and check the other pre-reqs to see if I can get it working. Will update if I do.

EDIT2: Nothing worked 😢 Still getting the same error. [Added ANDROID_HOME paths](https://stackoverflow.com/questions/26356359/error-android-home-is-not-set-and-android-command-not-in-your-path-you-must) and everything.

**Comment by mouti3** [comment]
Same problem

**Comment by Gosselk** [comment]
Same problem for me

**Comment by ghost** [comment]
Same problem (using Meteor 1.6)

**Comment by Gosselk** [comment]
i have found this :
`meteor npm i -g write-file-atomic path-is-inside async-some dezalgo`

it's work fine for add android and ios with meteor add-platform android

**Comment by erisevaline** [comment]
@Gosselk Worked for me, thanks !

**Comment by lflores1961** [comment]
Gosselk proposal won't work for me. Ubuntu 18.04; Node 8.10.0; npm 3.5.2
 $ meteor add-platform android
/home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Cannot find module 'dezalgo'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/lib/utils/correct-mkdir.js:2:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/lib/cache/get-stat.js:2:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/lib/cache/caching-client.js:12:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/lib/npm.js:23:24
    at Object.<anonymous> (/home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/lib/npm.js:475:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/registry/registry.js:20:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:32:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/plugman.js:33:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lflores/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/cordova-lib.js:33:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tools/cordova/project.js:1:1137)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at Module.Mp.load (/tools/tool-env/install-runtime.js:16:29)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at doAddPlatform (/tools/cli/commands-cordova.js:1:33)
    at Command.func (/tools/cli/commands-cordova.js:125:3)
    at /tools/cli/main.js:1523:15
